# Generated by Django 5.2.8 on 2025-11-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('top_sights', models.TextField(blank=True, help_text='Enter a comma-separated list of sights.')),
                ('famous_food', models.TextField(blank=True, help_text='Enter a comma-separated list of famous foods/items.')),
            ],
        ),
    ]
